# Generated by Django 3.0.4 on 2020-03-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
        ('projects', '0005_auto_20200318_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='category_id',
            new_name='c',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_content', models.TextField(default=' ')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.User')),
            ],
        ),
    ]
