# Generated by Django 3.0.4 on 2020-03-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200319_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='projects.Tag'),
        ),
    ]
