# Generated by Django 3.0.4 on 2020-03-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200319_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_img',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Projects'),
            preserve_default=False,
        ),
    ]
