# Generated by Django 3.0.4 on 2020-03-18 01:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=10)),
                ('user_lname', models.CharField(max_length=10)),
                ('user_picture', models.ImageField(upload_to='user_images/')),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
