# Generated by Django 3.0.4 on 2020-03-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200320_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_picture',
            field=models.ImageField(default='default.jpg', upload_to='user/static/profile_pics'),
        ),
    ]
