# Generated by Django 3.0.4 on 2020-03-20 04:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200320_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_id',
        ),
        migrations.AlterField(
            model_name='userphone',
            name='user_phone',
            field=models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.CASCADE, related_name='phone', to='user.Profile', validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')]),
        ),
    ]
