# Generated by Django 3.0.4 on 2020-03-20 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200320_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='userphone',
            name='phone',
            field=models.ForeignKey(blank=True, max_length=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Profile', validators=[django.core.validators.RegexValidator(regex='^[+-]?[0-9]+$')]),
        ),
    ]
