# Generated by Django 3.0.4 on 2020-03-19 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bith_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.TextField(max_length=300, null=True, validators=[django.core.validators.RegexValidator(regex='.+www.facebook.com\\/[^\\/]+$')]),
        ),
    ]
