# Generated by Django 3.0.4 on 2020-03-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_id',
        ),
        migrations.AddField(
            model_name='userphone',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userAuth.User'),
            preserve_default=False,
        ),
    ]
