# Generated by Django 3.0.4 on 2020-03-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200319_2246'),
        ('userAuth', '0002_auto_20200319_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPhone',
        ),
    ]
